use_utterances: True
penalize_words: False
n_epochs: 1
learning_rate: None
batch_size: 2
n_timesteps: 16
num_shapes: 4
num_colors: 4
max_agents: 3
min_agents: 3
max_landmarks: 5
min_landmarks: 5
vocab_size: 20
oov_prob: None
load_model_weights: None
save_model_weights: None
use_cuda: False
show_timestep: True
world_dim: 16
memory_size: 20